name: PR - Java TEST
on: [pull_request]

jobs:
  collect_dirs:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - id: dirs
        run: echo "::set-output name=dirs::$(find ./ -name javaSolution -type d | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')"

  run_tests:
    needs: collect_dirs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.collect_dirs.outputs.dirs) }}
    steps:
      - uses: actions/checkout@v3
      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ${{ matrix.dir }}/gradlew
      - name: Gradle 빌드 및 테스트
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: ${{ matrix.dir }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ matrix.dir }}
          separator: '/'
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results Java (${{ steps.split.outputs._1 }} ${{ steps.split.outputs._2 }} ${{ steps.split.outputs._3 }})
          path: ${{ matrix.dir }}/build/test-results/**/*.xml

  publish-test-results:
    name: "테스트 결과"
    needs: run_tests
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "artifacts/**/*.xml"
